version: '3'

services:
  phaser-socketio:
    container_name: phaser-socketio
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '80:80'
    environment:
      NODE_ENV: production